# input vcf with variants to be genotyped
vcf: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/data/pav-calls/pav_variants_freeze1_alt.vcf.gz"

# reference genome
reference: "/gpfs/project/projects/medbioinf/users/ebler/hgsvc3/data/reference/hg38.no_alt.fa"

# name of the output directory
outdir: "results-freeze1"

# optional: list specifying the gender of the samples
# present in the VCF (used to generate statistics). Format: <sample-name>	<1|2>
sample_info: "resources/sample-info.tsv"
